### ISSUE TITLE
Communicating between React and React Native using the webview

### ISSUE THREAD

**Issue by Titozzz** [React-Native-Amsterdam/talk-proposals#2]
### Title
Communicating between React and React Native using the webview

### Abstract
Let's create a simple app to demonstrate the ability to quickly create hybrid react/react-native applications. We will see how to seamlessly integrate the webview with react-navigation, and communicate data using the webview bridge.

### Your name (and pronouns)
Thibault Malbranche

### Contact Details

https://github.com/Titozzz/
https://twitter.com/Titozzz/

- [X] I need sponsorship

**Comment by lucasbento** [comment]
Closing this as it has been done, thank you for the talk @Titozzz!
