### ISSUE TITLE
React-Native-Web and Monorepo (How to make react-native work in the browser)

### ISSUE THREAD

**Issue by ronal2do** [React-Native-Amsterdam/talk-proposals#4]
### Title
React-Native-Web and Monorepo (How to make react-native work in the browser)

### Abstract

We will discover how easy and fun can be to share code between your applications - backend(_**Node**_), web(_**CRA**_), mobile(_**RN**_), desktop(_**Electron**_) with RNW and Yarn Workspaces .

**_Roadmap_**

- Fast introduction about _**RNW**_.
- Install e configure _**RNW**_ and set up to run on your browser.
- Share your _**tsconfig**_ between workspaces.
- Develop your agnostic RN-UI on the browser with _**Storybook**_.
- Use this UI on Web, Electron and RN.
- A trade-off between complexity and usability.

### Your name (and pronouns)
Ronaldo Lima
### Contact Details
[Twitter - @_2d_lima](https://twitter.com/_2d_lima)

**Comment by lucasbento** [comment]
Closing this as it has been done, thank you for the talk @ronal2do!

**Comment by pvinis** [comment]
when there is video, it would be cool to post this too in those issues :D

**Comment by lucasbento** [comment]
Good idea, we will do that @pvinis!
